<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>14</LangVersion>
    <RootNamespace>DashSpec.Connector.Postgres</RootNamespace>
    <AssemblyName>DashSpec.Connector.Postgres</AssemblyName>
    <Version>0.2.0</Version>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DashSpec.Abstractions\DashSpec.Abstractions.csproj" />
  </ItemGroup>

</Project>
