using DashSpec.Host.Configuration;

namespace DashSpec.Host.Services.Localization;

/// <summary>UI string localizer (remark 23: interface language switch). Default ru-RU, en fallback.</summary>
public sealed class DashboardLocalizer(DashSpecTomlRoot bootstrap)
{
    private bool Ru =>
        string.IsNullOrWhiteSpace(bootstrap.Presentation.Language) ||
        bootstrap.Presentation.Language.Trim().Equals("ru", StringComparison.OrdinalIgnoreCase);

    public string T(string key) => Ru ? RuMap(key) : En(key);

    private static string En(string key) => _en.TryGetValue(key, out var v) ? v : key;

    private static string RuMap(string key) => _ruMap.TryGetValue(key, out var v) ? v : En(key);

    private static readonly IReadOnlyDictionary<string, string> _ruMap =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["Dashboard"] = "Дашборд",
            ["Settings"] = "Настройки",
            ["Spec"] = "Спека",
            ["Reports"] = "Отчёты",
            ["Help"] = "Справка",
            ["Loading specification…"] = "Загрузка спецификации…",
            ["Failed to load dashboard"] = "Не удалось загрузить дашборд",
            ["Apply"] = "Применить",
            ["Reset"] = "Сбросить",
            ["Expand"] = "Развернуть",
            ["Collapse"] = "Свернуть",
            ["Expand diagram"] = "Развернуть диаграмму",
            ["Export CSV"] = "Экспорт CSV",
            ["Loading…"] = "загрузка…",
            ["Error"] = "ошибка",
            ["Date from"] = "Дата от",
            ["Date to"] = "Дата до",
            ["Field"] = "Поле",
            ["Top"] = "Топ",
            ["Users"] = "Пользователи",
            ["Utilization"] = "Загрузка",
            ["License load"] = "Загрузка лицензий",
            ["Report"] = "Отчёт",
            ["Page"] = "Страница",
            ["Tab"] = "Вкладка",
            ["Export"] = "Экспорт",
            ["Upload spec"] = "Загрузить спеку",
            ["Sync now"] = "Синхронизировать сейчас",
            ["Syncing…"] = "Синхронизация…",
            ["Save"] = "Сохранить",
            ["Save access"] = "Сохранить доступ",
            ["Save catalog"] = "Сохранить каталог",
            ["Save presentation"] = "Сохранить настройки отображения",
            ["Generate secret"] = "Сгенерировать секрет",
            ["Show export"] = "Показать экспорт",
            ["API key"] = "API-ключ",
            ["set — leave blank to keep"] = "задан — оставьте пустым для сохранения",
            ["Enabled"] = "Включено",
            ["URL"] = "URL",
            ["Branch"] = "Ветка",
            ["Path (.dashcatalog in repo)"] = "Путь (.dashcatalog в репозитории)",
            ["Pull interval (minutes, safety net)"] = "Интервал опроса (минут, страховка)",
            ["Git username"] = "Пользователь git",
            ["Git password"] = "Пароль git",
            ["Sync repo slug filter (optional)"] = "Фильтр slug репозитория (опционально)",
            ["Allow unsigned webhooks (lab only)"] = "Разрешить неподписанные вебхуки (только lab)",
            ["Display time zone (IANA id, e.g. Europe/Moscow; stored UTC → display TZ; remark 25)"] = "Часовой пояс отображения (IANA id, напр. Europe/Moscow; хранение UTC → вывод в TZ; замечание 25)",
            ["Applied on host restart. Empty = Europe/Moscow."] = "Применяется после перезапуска хоста. Пусто = Europe/Moscow.",
            ["Interface language (remark 23)"] = "Язык интерфейса (замечание 23)",
            ["Applied on host restart. Empty = ru-RU."] = "Применяется после перезапуска хоста. Пусто = ru-RU.",
            ["Long product filter lists (>80 items; remark 7)"] = "Длинные списки фильтра ПО (>80; замечание 7)",
            ["Scroll in a fixed area (default)"] = "Прокрутка в фиксированной области (по умолчанию)",
            ["Expand downward (full chip list)"] = "Раскрытие вниз (полный список чипов)",
            ["Applies immediately after save. Affects chips / multi-select filters with more than 80 options."] = "Применяется сразу после сохранения. Для chips / multi-select с более чем 80 значениями.",
            ["Presentation saved. Time zone / language apply after host restart; long filter layout applies immediately."] = "Настройки отображения сохранены. Часовой пояс и язык — после перезапуска; длинные фильтры — сразу.",
            ["Presentation saved. Restart host to apply new time zone."] = "Настройки отображения сохранены. Перезапустите хост для применения часового пояса.",
            ["Presentation saved. Restart host to apply new language."] = "Настройки отображения сохранены. Перезапустите хост для применения языка.",
            ["Secret:"] = "Секрет:",
            ["not set"] = "не задан",
            ["set"] = "задан",
            ["(copy now — not shown again)"] = "(скопируйте сейчас — больше не покажем)",
            ["Paste into Forge FORGE_DASHSPEC_WEBHOOK_URL + shared secret."] = "Вставьте в Forge FORGE_DASHSPEC_WEBHOOK_URL + общий секрет.",
            ["Runtime settings in WitDB (ADR-0042). Bootstrap TOML remains cold-start / disaster recovery."] = "Настройки времени выполнения в WitDB (ADR-0042). Bootstrap TOML остаётся для холодного старта / восстановления.",
            ["Redacted TOML fragment from WitDB for air-gap backup (does not write local.toml)."] = "Отредактированный TOML-фрагмент из WitDB для резервного копирования без сети (не записывает local.toml).",
        };

    private static readonly IReadOnlyDictionary<string, string> _en =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["Dashboard"] = "Dashboard",
            ["Settings"] = "Settings",
            ["Spec"] = "Spec",
            ["Reports"] = "Reports",
            ["Help"] = "Help",
            ["Loading specification…"] = "Loading specification…",
            ["Failed to load dashboard"] = "Failed to load dashboard",
            ["Apply"] = "Apply",
            ["Reset"] = "Reset",
            ["Expand"] = "Expand",
            ["Collapse"] = "Collapse",
            ["Expand diagram"] = "Expand diagram",
            ["Export CSV"] = "Export CSV",
            ["Loading…"] = "Loading…",
            ["Error"] = "Error",
            ["Date from"] = "Date from",
            ["Date to"] = "Date to",
            ["Field"] = "Field",
            ["Top"] = "Top",
            ["Users"] = "Users",
            ["Utilization"] = "Utilization",
            ["License load"] = "License load",
            ["Report"] = "Report",
            ["Page"] = "Page",
            ["Tab"] = "Tab",
            ["Export"] = "Export",
            ["Upload spec"] = "Upload spec",
            ["Sync now"] = "Sync now",
            ["Syncing…"] = "Syncing…",
            ["Save"] = "Save",
            ["Save access"] = "Save access",
            ["Save catalog"] = "Save catalog",
            ["Save presentation"] = "Save presentation",
            ["Generate secret"] = "Generate secret",
            ["Show export"] = "Show export",
            ["API key"] = "API key",
            ["set — leave blank to keep"] = "set — leave blank to keep",
            ["Enabled"] = "Enabled",
            ["URL"] = "URL",
            ["Branch"] = "Branch",
            ["Path (.dashcatalog in repo)"] = "Path (.dashcatalog in repo)",
            ["Pull interval (minutes, safety net)"] = "Pull interval (minutes, safety net)",
            ["Git username"] = "Git username",
            ["Git password"] = "Git password",
            ["Sync repo slug filter (optional)"] = "Sync repo slug filter (optional)",
            ["Allow unsigned webhooks (lab only)"] = "Allow unsigned webhooks (lab only)",
            ["Display time zone (IANA id, e.g. Europe/Moscow; stored UTC → display TZ; remark 25)"] = "Display time zone (IANA id, e.g. Europe/Moscow; stored UTC → display TZ; remark 25)",
            ["Applied on host restart. Empty = Europe/Moscow."] = "Applied on host restart. Empty = Europe/Moscow.",
            ["Interface language (remark 23)"] = "Interface language (remark 23)",
            ["Applied on host restart. Empty = ru-RU."] = "Applied on host restart. Empty = ru-RU.",
            ["Long product filter lists (>80 items; remark 7)"] = "Long product filter lists (>80 items; remark 7)",
            ["Scroll in a fixed area (default)"] = "Scroll in a fixed area (default)",
            ["Expand downward (full chip list)"] = "Expand downward (full chip list)",
            ["Applies immediately after save. Affects chips / multi-select filters with more than 80 options."] = "Applies immediately after save. Affects chips / multi-select filters with more than 80 options.",
            ["Presentation saved. Time zone / language apply after host restart; long filter layout applies immediately."] = "Presentation saved. Time zone / language apply after host restart; long filter layout applies immediately.",
            ["Presentation saved. Restart host to apply new time zone."] = "Presentation saved. Restart host to apply new time zone.",
            ["Presentation saved. Restart host to apply new language."] = "Presentation saved. Restart host to apply new language.",
            ["Secret:"] = "Secret:",
            ["not set"] = "not set",
            ["set"] = "set",
            ["(copy now — not shown again)"] = "(copy now — not shown again)",
            ["Paste into Forge FORGE_DASHSPEC_WEBHOOK_URL + shared secret."] = "Paste into Forge FORGE_DASHSPEC_WEBHOOK_URL + shared secret.",
            ["Runtime settings in WitDB (ADR-0042). Bootstrap TOML remains cold-start / disaster recovery."] = "Runtime settings in WitDB (ADR-0042). Bootstrap TOML remains cold-start / disaster recovery.",
            ["Redacted TOML fragment from WitDB for air-gap backup (does not write local.toml)."] = "Redacted TOML fragment from WitDB for air-gap backup (does not write local.toml).",
        };
}
