<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>14</LangVersion>
    <RootNamespace>DashSpec.Surface.Blazor</RootNamespace>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DashSpec.Core\DashSpec.Core.csproj" />
    <ProjectReference Include="..\DashSpec.Execution.Compilation\DashSpec.Execution.Compilation.csproj" />
    <ProjectReference Include="..\DashSpec.Execution.Core\DashSpec.Execution.Core.csproj" />
    <ProjectReference Include="..\DashSpec.Presentation\DashSpec.Presentation.csproj" />
    <ProjectReference Include="..\DashSpec.Viz\DashSpec.Viz.csproj" />
  </ItemGroup>
</Project>
